version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/html:/usr/share/nginx/html

  varnish:
    image: varnish:fresh-alpine
    depends_on:
      - nginx
    links:
      - nginx
    volumes:
      - ./varnish/conf/default.vcl:/etc/varnish/default.vcl
    ports:
      - 5002:80